### checking out scikit learn


In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = [0,2,1,3]
y_true = [0,1,2,3]
accuracy_score(y_true, y_pred)
#output shows 0.5 means 50% accuracy since 2 out 4 data were correct
accuracy_score(y_true, y_pred, normalize = False)
#output shows 2 bcoz 2 of the data were true.

2

### checking out panda function

In [2]:
import pandas as pd

# create a simple dataset of people
data = {'Name': ["জসিম", "করিম", "মিতা", "অন্তরা"],
        'Location' : ["রাজশাহী", "ঢাকা", "রংপুর", "কুষ্টিয়া"],
        'Age' : [24, 13, 53, 33]
       }

frame = pd.DataFrame(data)

display(frame)

Name  Location  Age
0    জসিম   রাজশাহী   24
1    করিম      ঢাকা   13
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

In [3]:
#trying out some query
display(frame[frame.Age > 30])

Name  Location  Age
2    মিতা     রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

### checking out numpy

In [4]:
#creating array with numpy
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#creating multidimensional(3*4) array

import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # 3*4 array[3ta row, 4ta column]
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#we'll slice our array

b= a[:2, 1:3] #[row, column],python e indexing 0 theke start. row(:2)diye 0,1 row neya hoy bujhacche coz last num(2) baad pore
print(b)
#same column er khetre o...1,2 no column neya hocche, 0,3 baad

[[2 3]
 [6 7]]


In [8]:
c = a[:2] #ekhane slicing shudhu matro row slicing kora hocche coz 2nd kono comma nei...(0,1) row neya hocche
print(c)

[[1 2 3 4]
 [5 6 7 8]]


### function

In [10]:
def double(x):
    return x*2

print(double(3))

6


In [12]:
def square(x):
    return x*x

print(square(3))

9


### dictionary

In [13]:
tel = {'rafiq': 4098, 'mim': 4139}
tel['karim'] = 4127
tel

{'rafiq': 4098, 'mim': 4139, 'karim': 4127}

In [14]:
tel['mim']

4139

In [28]:
# looping dictionary items

mlbooks = {'data science from scratch': 'joel grus', 'python data scince handbook': 'jake vanderplas'}

for x,y in mlbooks.items():
    print(x,y)

data science from scratch joel grus
python data scince handbook jake vanderplas


### for loop, if/else condition

In [7]:
words = ['cat','window','door']
for x in words:
    print(x, len(x))

cat 3
window 6
door 4


### lists

In [8]:
squares = [1,4,9,16,25,36]
squares

[1, 4, 9, 16, 25, 36]

In [9]:
squares[-1]

36

In [13]:
squares[:3]

[1, 4, 9]

### normal expression

In [14]:
width = 20
height = 5*6
square = width*height
print(square)

600


In [26]:
tax = 12.5/100
price = 100.50
price*tax

12.5625

In [27]:
price+_ #ekhane (_) last j value sheita k add kortese

113.0625

In [28]:
round(_,2) #2 decimal point porjonto round kortese

113.06

### pass

In [29]:
# pass is just a placeholder for functionality to be added later
sequence = {'p','a','s','s'}
for val in sequence:
    pass

In [30]:
def function(args):
    pass

In [31]:
class example:
    pass

### dir() function

In [33]:
from sklearn import datasets
iris = datasets.load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [40]:
import pandas as pd
data = pd.read_csv('chirps.csv')
dir(data)

['Chirps_15s',
 'Date',
 'T',
 'Temp_C',
 'Time',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '_

In [42]:
print(data)

      Date  Time  Chirps_15s   Temp_C
0   21-Aug  2030      44.000  26.9440
1   21-Aug  2100      46.400  25.8330
2   21-Aug  2200      43.600  25.5560
3   24-Aug  1945      35.000  23.0560
4   24-Aug  2015      35.000  21.3890
5   24-Aug  2100      32.600  20.0000
6   24-Aug  2200      28.900  18.8890
7   24-Aug  2230      27.700  18.3330
8   25-Aug    30      25.500  16.3890
9   25-Aug   330      20.375  13.8890
10  25-Aug   500      12.500  12.7780
11  25-Aug  2000      37.000  24.5830
12  25-Aug  2030      37.500  23.3330
13  25-Aug  2100      36.500  23.3330
14  25-Aug  2200      36.200  22.5000
15  26-Aug   530      33.000  18.8890
16  26-Aug  2030      43.000  25.2780
17  26-Aug  2200      46.000  25.8330
18  27-Aug  2000      29.000  20.2780
19  27-Aug  2030      31.700  20.2780
20  27-Aug  2100      31.000  20.0000
21  27-Aug  2200      28.750  18.8890
22  28-Aug   240      23.500  15.0000
23  28-Aug  2010      32.400  21.1110
24  28-Aug  2050      31.000  20.5560
25  28-Aug  

In [43]:
data

Date  Time  Chirps_15s   Temp_C
0   21-Aug  2030      44.000  26.9440
1   21-Aug  2100      46.400  25.8330
2   21-Aug  2200      43.600  25.5560
3   24-Aug  1945      35.000  23.0560
4   24-Aug  2015      35.000  21.3890
5   24-Aug  2100      32.600  20.0000
6   24-Aug  2200      28.900  18.8890
7   24-Aug  2230      27.700  18.3330
8   25-Aug    30      25.500  16.3890
9   25-Aug   330      20.375  13.8890
10  25-Aug   500      12.500  12.7780
11  25-Aug  2000      37.000  24.5830
12  25-Aug  2030      37.500  23.3330
13  25-Aug  2100      36.500  23.3330
14  25-Aug  2200      36.200  22.5000
15  26-Aug   530      33.000  18.8890
16  26-Aug  2030      43.000  25.2780
17  26-Aug  2200      46.000  25.8330
18  27-Aug  2000      29.000  20.2780
19  27-Aug  2030      31.700  20.2780
20  27-Aug  2100      31.000  20.0000
21  27-Aug  2200      28.750  18.8890
22  28-Aug   240      23.500  15.0000
23  28-Aug  2010      32.400  21.1110
24  28-Aug  2050      31.000  20.5560
25  28-Aug  2200      29.500  19.4440
26  29-Aug   240      22.500  16.2500
27  29-Aug   440      20.600  14.7220
28  29-Aug  2000      35.000  22.2220
29  29-Aug  2050      33.100  21.6670
30  29-Aug  2200      31.500  20.5560
31  29-Aug  2330      28.800  19.1670
32  30-Aug   330      21.300  15.5560
33  30-Aug  2000      37.800  23.8890
34  30-Aug  2055      37.000  22.9170
35  30-Aug  2200      37.100  22.5000
36   1-Sep  2200      36.200  21.1110
37   2-Sep   330      31.400  19.7220
38   2-Sep   600      30.200  18.8890
39   4-Sep   240      31.300  20.5560
40   4-Sep   505      26.100  17.2220
41   5-Sep   500      25.200  17.2220
42   6-Sep   600      23.660  16.1110
43   7-Sep   215      22.250  16.6670
44   7-Sep   525      17.500  13.6110
45   9-Sep  2010      15.500  12.7780
46   9-Sep  2110      14.750  11.1110
47  10-Sep  2115      15.000  11.6670
48  10-Sep  2210      14.000  10.0000
49  11-Sep   315      18.500  11.1110
50  16-Sep  2100      27.700  18.3330
51  17-Sep  2200      26.000  17.2220
52  18-Sep   130      21.700  15.0000
53  19-Sep   415      12.500  10.4170
54  19-Sep   435      12.500   9.5833